server:
  port: 8080

spring:
  application:
    name: immopulse-api

  datasource:
    postgres:
      url: jdbc:postgresql://localhost:5432/default_database
      username: username
      password: password
      driver-class-name: org.postgresql.Driver
    clickhouse:
      url: jdbc:clickhouse://localhost:8123/default?compress=0
      username: username
      password: password
      driver-class-name: com.clickhouse.jdbc.ClickHouseDriver

  jpa:
    show-sql: true # to display SQL queries in the console
    hibernate:
      ddl-auto: update # to let Spring create the schema by running migrations

logging:
  level:
    org:
      springframework:
        web: DEBUG

springdoc:
  swagger-ui:
    path: /api/docs

management:
  tracing:
    sampling:
      probability: '1.0'
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 10s
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
    logging:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/logs
  observations:
    annotations:
      enabled: true
